pipeline:

  kustomize:
    image: bitlayer/kustomize:v2.0.3
    commands:
      - cd kube && kustomize build > ../kustomize.out
    when:
      # event: tag
      event: push

  deploy-to-kube:
    image: quay.io/ukhomeofficedigital/kd:v1.10.6
    secrets:
      - kube_token_acp_notprod
    environment:
      - DRONE_DEPLOY_TO=acp-notprod
      - IMAGE_URL=http://quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb:v0.1.0
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh kustomize.out
    when:
      # event: tag
      event: push

#  build_ecr:
#    image: quay.io/ukhomeofficedigital/ecr:latest
#    secrets:
#      - AWS_ACCESS_KEY_ID
#      - AWS_SECRET_ACCESS_KEY
#    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp-induction/leonardo
#    tags:
#    - ${DRONE_COMMIT_SHA}
#    when:
#      event: push

#  build_tag_ecr:
#    image: quay.io/ukhomeofficedigital/ecr:latest
#    secrets:
#      - ACCESS_ID
#      - ACCESS_KEY
#    repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp-induction/leonardo
#    tags:
#      - latest
#      - ${DRONE_TAG}
#    when:
#      event: tag
