---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tinkerpop-graphdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tinkerpop-graphdb
    spec:
      containers:
        - name: tinkerpop-graphdb
          image: http://quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /opt/graphdb/conf
              name: config
              readOnly: true
          env: 
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tinkerpop-graphdb
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tinkerpop-graphdb
                  key: AWS_SECRET_ACCESS_KEY


            - name: AWS_DEFAULT_REGION
              value: eu-west-2

      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: tinkerpop-graphdb
