---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tinkerpop-graphdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tinkerpop-graphdb
    spec:
      containers:
        - name: tinkerpop-graphdb
          image: quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb:v0.1.1
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /opt/graphdb/conf
              name: config
              readOnly: true
          env: 
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tinkerpop-graphdb
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tinkerpop-graphdb
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: eu-west-2
            - name: PVGDPR_OPTS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap  -Dcom.sun.management.jmxremote
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 4Gi
          readinessProbe:
            httpGet:
              path: /healthcheck/readiness
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthcheck/liveliness
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 30
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: tinkerpop-graphdb
