apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tinkerpop-graphdb
    files:
      - conf/gremlin-server.yml
      - conf/janusgraph-dynamodb.properties

secretGenerator:
  - name: tinkerpop-graphdb
    type: Opaque
    env: awscreds.txt

